
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 10;
  public static final int BOX = 6;
  public static final int SATIS = 4;
  public static final int NOM = 12;
  public static final int RPARAN = 3;
  public static final int LPARAN = 2;
  public static final int EOF = 0;
  public static final int DIA = 5;
  public static final int IMP = 7;
  public static final int error = 1;
  public static final int NOT = 9;
  public static final int BIIMP = 8;
  public static final int OR = 11;
  public static final int PROP = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPARAN",
  "RPARAN",
  "SATIS",
  "DIA",
  "BOX",
  "IMP",
  "BIIMP",
  "NOT",
  "AND",
  "OR",
  "NOM",
  "PROP"
  };
}

